apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-microservices-shipments
  labels:
    app: contoso
    microservice: shipments
spec:
  selector:
    matchLabels:
      app: contoso
      microservice: shipments
  template:
    metadata:
      labels:
        app: contoso
        microservice: shipments
    spec:
      containers:
      - name: shipments-api
        image: ghcr.io/tomkerkhove/microservices-with-api-management-services-shipment:latest
        ports:
        - containerPort: 80
        env:
        - name: AZURESTORAGE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
             name: shipments-secrets
             key: AZURESTORAGE_CONNECTIONSTRING
        livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
        readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: contoso-microservices-shipments-loadbalancer-service
  labels:
    app: contoso
    microservice: shipments
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: contoso-shipments-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8890
      targetPort: 80
      protocol: TCP
  selector:
    app: contoso
    microservice: shipments
---
apiVersion: v1
kind: Service
metadata:
  name: contoso-microservices-shipments-internal-service
  labels:
    app: contoso
    microservice: shipments
spec:
  ports:
  - port: 88
    targetPort: 80
    protocol: TCP
  selector:
    app: contoso
    microservice: shipments
---
apiVersion: v1
kind: Secret
metadata:
  name: shipments-secrets
  labels:
    app: contoso
    microservice: shipments
data:
  AZURESTORAGE_CONNECTIONSTRING: <base64 encoded connection string>